version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: always

  db:
    image: "postgres:15"
    env_file:
      - ./.env
    restart: always
    ports:
      - "9432:5432"
    volumes:
      - /tmp/postgresql:/var/lib/postgresql
      - /tmp/postgresql/data:/var/lib/postgresql/data
