"""empty message

Revision ID: bfa913fc28a4
Revises: c860b3ff27db
Create Date: 2023-07-14 13:18:01.292576

"""

# revision identifiers, used by Alembic.
revision = 'bfa913fc28a4'
down_revision = 'c860b3ff27db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
