"""initial

Revision ID: c860b3ff27db
Revises: 
Create Date: 2023-07-14 13:14:32.766298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c860b3ff27db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('authors_name_key', 'authors', type_='unique')
    op.add_column('books', sa.Column('reserved_datatime', sa.Integer(), nullable=True))
    op.drop_column('books', 'reserved_datetime')
    op.drop_constraint('genres_name_key', 'genres', type_='unique')
    op.drop_constraint('publishers_name_key', 'publishers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('publishers_name_key', 'publishers', ['name'])
    op.create_unique_constraint('genres_name_key', 'genres', ['name'])
    op.add_column('books', sa.Column('reserved_datetime', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('books', 'reserved_datatime')
    op.create_unique_constraint('authors_name_key', 'authors', ['name'])
    # ### end Alembic commands ###
